import Navigation from "@/components/Navigation";
import "@fontsource/ibm-plex-mono";
import "@fontsource/poppins";
import "./globals.css";
import Footer from "@/components/sections/Footer";

export const metadata = {
  title: "Namespace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
